// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQihS3L0yI6VAQN-HlazubsTLkKEAM3FI',
    appId: '1:304366231052:web:9bb4e9207bbdc8cf5c5829',
    messagingSenderId: '304366231052',
    projectId: 'lodger-bf115',
    authDomain: 'lodger-bf115.firebaseapp.com',
    storageBucket: 'lodger-bf115.appspot.com',
    measurementId: 'G-2DQCQ1MJSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4enwz_SVfRIWBb-zL3DJKksRmQMzwtw',
    appId: '1:304366231052:android:d01e01262f536bb55c5829',
    messagingSenderId: '304366231052',
    projectId: 'lodger-bf115',
    storageBucket: 'lodger-bf115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDJLwaHr0vptHlPf3JVTQTGLoiKh8e6_o',
    appId: '1:304366231052:ios:b6bf4dc9b6184c205c5829',
    messagingSenderId: '304366231052',
    projectId: 'lodger-bf115',
    storageBucket: 'lodger-bf115.appspot.com',
    iosClientId: '304366231052-ipejhm80brcf0j49g92lfi2snv3nmdgc.apps.googleusercontent.com',
    iosBundleId: 'com.lodger.app',
  );
}
